#!/bin/bash
set -e

# Usage: ./scripts/generate_env.sh <env>
# where <env> is 'local', 'dev', or 'prd'

ENV_NAME=${1:-"local"}
ENV_FILE=".env.${ENV_NAME}"
AWS_PROFILE=${AWS_PROFILE:-"dev"}

echo "Generating $ENV_FILE for environment: $ENV_NAME..."

if [ "$ENV_NAME" == "local" ]; then
  # Local environment uses existing dev DSQL and DynamoDB
  echo "# Local environment configuration" > $ENV_FILE
  echo "AWS_PROFILE=$AWS_PROFILE" >> $ENV_FILE
  echo "AWS_REGION=ap-northeast-1" >> $ENV_FILE
  echo "" >> $ENV_FILE
  echo "# DB Configuration (using existing dev resources)" >> $ENV_FILE
  echo "DSQL_ENDPOINT=arn:aws:dsql:ap-northeast-1:031921999648:cluster/drtscvjcc62yqrtpzcwyybwnem" >> $ENV_FILE
  echo "" >> $ENV_FILE
  echo "# Cache Configuration (using existing dev resources)" >> $ENV_FILE
  echo "DYNAMO_TABLE=version-checker-dev-eol-cache" >> $ENV_FILE
  echo "REPO_CACHE_TABLE=version-checker-dev-repo-cache" >> $ENV_FILE
  echo "REPO_CACHE_TTL_SECONDS=180" >> $ENV_FILE
  echo "SCAN_QUEUE_URL=" >> $ENV_FILE
  echo "" >> $ENV_FILE
  echo "# Backend API (Local)" >> $ENV_FILE
  echo "FRONTEND_BASE_URL=http://localhost:3000" >> $ENV_FILE
  echo "CORS_ALLOW_ORIGINS=http://localhost:3000" >> $ENV_FILE
  echo "NUXT_PUBLIC_API_BASE=http://localhost:8000/api/v1" >> $ENV_FILE
  echo "" >> $ENV_FILE
  echo "# --- Manual Configuration ---" >> $ENV_FILE
  echo "GITHUB_CLIENT_ID=Iv23lieWadcmF5sJusQw" >> $ENV_FILE
  echo "GITHUB_CLIENT_SECRET=aa8cf88e406f972e8aa6f05eeeb68e0472239755" >> $ENV_FILE

elif [ "$ENV_NAME" == "dev" ] || [ "$ENV_NAME" == "prd" ]; then
  # dev/prd environments use Terraform outputs
  # Preserve manual variables (GitHub tokens)
  MANAGED_KEYS="AWS_PROFILE|AWS_REGION|DSQL_ENDPOINT|DYNAMO_TABLE|REPO_CACHE_TABLE|REPO_CACHE_TTL_SECONDS|SCAN_QUEUE_URL|LAMBDA_BACKEND_URL|API_GATEWAY_URL|FRONTEND_BASE_URL|NUXT_PUBLIC_API_BASE|CORS_ALLOW_ORIGINS"

  PRESERVED=""
  if [ -f "$ENV_FILE" ]; then
    PRESERVED=$(grep -vE "^#.*(Auto-generated|DB Configuration|Cache Configuration|Backend API)" "$ENV_FILE" \
      | grep -vE "^($MANAGED_KEYS)=" \
      | sed '/^$/d' || true)
  fi

  cd terraform || exit 1

  # Select workspace
  WORKSPACE=$(terraform workspace show)
  if [ "$WORKSPACE" != "$ENV_NAME" ]; then
    terraform workspace select "$ENV_NAME" || terraform workspace new "$ENV_NAME"
  fi

  DSQL_ENDPOINT=$(terraform output -raw dsql_endpoint || echo "")
  DYNAMO_TABLE=$(terraform output -raw dynamodb_table_name || echo "")
  REPO_CACHE_TABLE="version-checker-${ENV_NAME}-repo-cache"
  REPO_CACHE_TTL_SECONDS="180"
  SCAN_QUEUE_URL=$(terraform output -raw scan_queue_url || echo "")
  LAMBDA_BACKEND_URL=$(terraform output -raw lambda_backend_url || echo "")
  API_GATEWAY_URL=$(terraform output -raw api_base_url || echo "")
  FRONTEND_BASE_URL=$(terraform output -raw frontend_base_url || echo "")

  cd ..

  # Construct frontend API URL from API Gateway custom domain
  NUXT_PUBLIC_API_BASE="${API_GATEWAY_URL}/api/v1"
  CORS_ALLOW_ORIGINS="http://localhost:3000,${FRONTEND_BASE_URL}"

  cat <<EOF > $ENV_FILE
# Auto-generated by generate_env.sh for environment: $ENV_NAME
AWS_PROFILE=$AWS_PROFILE
AWS_REGION=ap-northeast-1

# DB Configuration
DSQL_ENDPOINT=$DSQL_ENDPOINT

# Cache Configuration
DYNAMO_TABLE=$DYNAMO_TABLE
REPO_CACHE_TABLE=$REPO_CACHE_TABLE
REPO_CACHE_TTL_SECONDS=$REPO_CACHE_TTL_SECONDS
SCAN_QUEUE_URL=$SCAN_QUEUE_URL

# Backend API
LAMBDA_BACKEND_URL=$LAMBDA_BACKEND_URL
API_GATEWAY_URL=$API_GATEWAY_URL
FRONTEND_BASE_URL=$FRONTEND_BASE_URL

# Frontend API URL
NUXT_PUBLIC_API_BASE=$NUXT_PUBLIC_API_BASE
CORS_ALLOW_ORIGINS=$CORS_ALLOW_ORIGINS
EOF

  # Append preserved manual settings
  if [ -n "$PRESERVED" ]; then
    echo "" >> $ENV_FILE
    echo "# --- Manual Configuration (preserved) ---" >> $ENV_FILE
    echo "$PRESERVED" >> $ENV_FILE
  fi

else
  echo "Error: Invalid environment '$ENV_NAME'. Use 'local', 'dev', or 'prd'."
  exit 1
fi

echo "$ENV_FILE generated successfully."
cat $ENV_FILE
