#!/bin/bash
set -e

ENV_FILE=".env"
AWS_PROFILE=${AWS_PROFILE:-"dev"}

echo "Generating $ENV_FILE from Terraform outputs..."

# --- Preserve manually added variables ---
# These keys are managed by this script (Terraform outputs).
# Everything else in .env is considered "manual" and will be preserved.
MANAGED_KEYS="AWS_PROFILE|AWS_REGION|DSQL_ENDPOINT|DYNAMO_TABLE"

PRESERVED=""
if [ -f "$ENV_FILE" ]; then
  # Extract lines that are NOT comments about auto-generation,
  # NOT blank lines adjacent to managed keys, and NOT managed keys themselves.
  PRESERVED=$(grep -vE "^#.*(Auto-generated|DB Configuration|Cache Configuration)" "$ENV_FILE" \
    | grep -vE "^($MANAGED_KEYS)=" \
    | sed '/^$/d' || true)
fi

# Ensure we are in terraform directory for pulling outputs
cd terraform || exit 1

# Check current workspace
WORKSPACE=$(terraform workspace show)
echo "Current Terraform Workspace: $WORKSPACE"

if [ -z "$WORKSPACE" ] || [ "$WORKSPACE" == "default" ]; then
  echo "Error: Please run 'terraform workspace select dev' (or prd) first."
  exit 1
fi

DSQL_ENDPOINT=$(terraform output -raw dsql_endpoint || echo "")
DYNAMO_TABLE=$(terraform output -raw dynamodb_table_name || echo "")

cd ..

# Write Terraform-managed section
cat <<EOF > $ENV_FILE
# Auto-generated by generate_local_env.sh for workspace: $WORKSPACE
AWS_PROFILE=$AWS_PROFILE
AWS_REGION=ap-northeast-1

# DB Configuration
DSQL_ENDPOINT=$DSQL_ENDPOINT

# Cache Configuration
DYNAMO_TABLE=$DYNAMO_TABLE

# Frontend + CORS
FRONTEND_BASE_URL=http://localhost:3000
CORS_ALLOW_ORIGINS=http://localhost:3000
EOF

# Append preserved manual settings
if [ -n "$PRESERVED" ]; then
  echo "" >> $ENV_FILE
  echo "# --- Manual Configuration (preserved) ---" >> $ENV_FILE
  echo "$PRESERVED" >> $ENV_FILE
fi

echo "$ENV_FILE generated successfully."
cat $ENV_FILE
