#!/bin/bash
set -e

ENV_FILE=".env"
AWS_PROFILE=${AWS_PROFILE:-"dev"}

echo "Generating $ENV_FILE from Terraform outputs..."

# Ensure we are in terraform directory for pulling outputs
cd terraform || exit 1

# Check current workspace
WORKSPACE=$(terraform workspace show)
echo "Current Terraform Workspace: $WORKSPACE"

if [ -z "$WORKSPACE" ] || [ "$WORKSPACE" == "default" ]; then
  echo "Error: Please run 'terraform workspace select dev' (or prd) first."
  exit 1
fi

DSQL_ENDPOINT=$(terraform output -raw dsql_endpoint || echo "")
DYNAMO_TABLE=$(terraform output -raw dynamodb_table_name || echo "")

cd ..

cat <<EOF > $ENV_FILE
# Auto-generated by generate_local_env.sh for workspace: $WORKSPACE
AWS_PROFILE=$AWS_PROFILE
AWS_REGION=ap-northeast-1

# DB Configuration
DSQL_ENDPOINT=$DSQL_ENDPOINT

# Cache Configuration
DYNAMO_TABLE=$DYNAMO_TABLE
EOF

echo "$ENV_FILE generated successfully."
cat $ENV_FILE
